### ISSUE TITLE
0.6.3 seems to have been published with no artifacts

### ISSUE THREAD

**Issue by wrootie** [Bandwidth/node-webrtc#20]
When I installed @bandwidth/webrtc, got a successful installation message, but did not get any artifacts. 

The current version in the repo is 0.6.0, and while browsing the the last few commits, it appears y'all have been working on the CD code. 

Can y'all verify that the package has been published properly?

0.5.0 came down correctly, but there wasn't an option to install 0.6.3 (In the npm UI or by using yarn). 

Currently we have a workaround by pegging it to a specific commit - but we would rather not do this :)

**Comment by ajrice6713** [comment]
Hey Ruth,

I just tried to install `@bandwidth/webrtc` in a fresh node project and got 0.6.3 to install successfully using the npm CLI tool 

```
npm init
npm i @bandwidth/webrtc
```

are you able to provide any screen caps or steps to replicate?

**Comment by wrootie** [comment]
Appears it's a corrupted yarn cache issue - thanks for the response anyways!

`yarn cache clean @bandwidth/webrtc` fixed the issue for me
